import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { headers } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import { NavBar } from "./_components/NavBar";
import { Suspense } from "react";
import { Spinner } from "./_components/Spinner";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Ukrainian Drone League",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/drone_log.svf" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider headers={headers()}>
          <main className="flex min-h-screen flex-col bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white ">
            <NavBar />
            <Suspense fallback={<Spinner />}>{children}</Suspense>
          </main>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
